Add application icons
marhkb/pods pull request #167
Opened 2022-05-03 14:53 UTC by allaeddineomc

Resolves #99

2022-05-03 18:50 UTC, marhkb requested changes

2022-05-03 18:50 UTC, marhkb commented on src/application.rs
> +            .artists(vec!["Marcus Behrendt".into(), "Allaeddine Boulefaat".into()])
rustfmt complains. This should fix it.
```suggestion
            .artists(vec![
                "Marcus Behrendt".into(),
                "Allaeddine Boulefaat".into(),
            ])
```

2022-05-03 18:53 UTC, marhkb commented
There is one thing I noticed: The icon appears a bit too small. Could you make it the same height and width like nautilus?

![comparison](https://user-images.githubusercontent.com/3630213/166522729-80e00127-b627-4953-94ad-827c87e40787.png)

2022-05-03 20:42 UTC, marhkb commented
Thanks. I noticed there's a problem with the symbolic icon. It's rendered dark instead of white. Can you  confirm?

![Bildschirmfoto vom 2022-05-03 22-40-04](https://user-images.githubusercontent.com/3630213/166562556-c8cd6ecd-0bed-43f7-b400-b674bdbbab09.png)
![Bildschirmfoto vom 2022-05-03 22-41-16](https://user-images.githubusercontent.com/3630213/166562562-06b895c0-d229-448e-93bb-00a94ca279d8.png)

2022-05-03 20:53 UTC, allaeddineomc commented
> Thanks. I noticed there's a problem with the symbolic icon. It's rendered dark instead of white. Can you confirm?
> 
> ![Bildschirmfoto vom 2022-05-03 22-40-04](https://user-images.githubusercontent.com/3630213/166562556-c8cd6ecd-0bed-43f7-b400-b674bdbbab09.png) ![Bildschirmfoto vom 2022-05-03 22-41-16](https://user-images.githubusercontent.com/3630213/166562562-06b895c0-d229-448e-93bb-00a94ca279d8.png)

yes i just noticed , i have no idea how to fix this , it renders correctly inside app icon preview but it's black when exported

2022-05-03 21:02 UTC, marhkb commented
I think I know why.

There is a general problem with the icons itself. Inside the svg you seem to import a png, which is not great because it may render them blurry and GNOME Shell cannot recolor the icons. 

The icons should only consist of geometry elements.

2022-05-03 21:10 UTC, allaeddineomc commented
so that's an issue with app icon preview app itself , the symbolic icon is vector in the source SVG but it's being exported as a PNG when using app icon preview , i will make it to it's own SVG file manually

2022-05-03 22:21 UTC, allaeddineomc commented
![Screenshot from 2022-05-03 23-20-20](https://user-images.githubusercontent.com/57415185/166577524-7981b623-5e4c-4809-bc18-1b2c6a0e055c.png)

2022-05-03 22:44 UTC, marhkb commented
Yes, that looks good. The other icons need to be changed, too. They also have an embedded pngs.

2022-05-04 12:21 UTC, marhkb commented
It's good now. At last, for merging, I need you to squash all the 5 commits into a single commit.

2022-05-04 13:03 UTC, allaeddineomc commented
done

2022-05-04 13:56 UTC, merged