feat: Add a way to set labels when creating a container
marhkb/pods pull request #343
Opened 2022-09-25 18:39 UTC by vv9k

This PR reworks the existing `EnvVarRow` to a more generic `KeyValRow` in order to be reused for labels. For now it has a predefined header labels `Key` and `Value` as I think it fits both env vars and labels so if there is a need to change the headers it might be implemented in the future PRs.

![image](https://user-images.githubusercontent.com/46892771/192159826-22add491-df4f-462f-b4e7-e3a7176ac99d.png)

Closes: #334

2022-09-25 19:41 UTC, marhkb requested changes

2022-09-25 19:41 UTC, marhkb commented on data/resources/resources.gresource.xml
> +    <file compressed="true" preprocess="xml-stripblanks">ui/key-val/row.ui</file>
This line needs to be moved a few lines down to keep the list sorted.

2022-09-25 19:52 UTC, marhkb commented
Thank you. :-)

Almost LGTM. 
I've just one small change request regarding the code and one regarding the commit messages. Could you tag the commits like for example:
```
refactor(env-var-row): Transform it into a more generic KeyValRow
feat(container-creation-page): Add a widget for defining labels
```

It doesn't matter if the length exceeds 50 characters, up to [72](https://wiki.gnome.org/Git/CommitMessages) are ok for me.

2022-09-26 05:31 UTC, vv9k commented
Done, made the list sorted and fixed the commit messages.

2022-09-26 07:28 UTC, vv9k commented
I was also considering expanding the image build page as well as pods creation page to also include the labels. Do you think it would be best to also introduce a AdwViewStack in image build page and put labels in the integration tab to match the container creation page?

2022-09-26 15:18 UTC, marhkb requested changes

2022-09-26 15:18 UTC, marhkb commented on data/resources/ui/image/build-page.ui
> -
The blank space should be kept here.

2022-09-26 15:18 UTC, marhkb commented on data/resources/ui/image/build-page.ui
> -
The blank space should be kept here.

2022-09-26 15:23 UTC, marhkb commented
> I was also considering expanding the image build page as well as pods creation page to include the labels as well. Do you think it would be best to also introduce a AdwViewStack in image build page and put labels in the integration tab to match the container creation page?

LGTM. Nice work. This can land if you resolve the two small change requests I made and the conflict.

2022-09-26 15:32 UTC, vv9k commented
Awesome :) fixed the outstanding issues with whitespace so should be ready for merge.

2022-09-26 17:26 UTC, marhkb approved these changes

2022-09-26 17:28 UTC, merged

2022-09-26 17:29 UTC, marhkb commented
Thanks :-)